# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      # For ab (apachebench) tests
      - apache2-utils

r:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - devel


env:
  global:
    - MAKEFLAGS="-j 2"
